# Generated by Django 3.2.5 on 2022-05-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=100)),
                ('candidateID', models.CharField(max_length=100)),
                ('candidateCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionRetroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('election_type', models.CharField(max_length=100)),
                ('acNum', models.CharField(max_length=100)),
                ('accName', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('partyName', models.CharField(max_length=100)),
                ('partyID', models.CharField(max_length=100)),
                ('alliance', models.CharField(max_length=100)),
                ('votesPolled', models.CharField(max_length=100)),
                ('totalValidVotes', models.CharField(max_length=100)),
                ('candidateName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.candidatedata')),
            ],
        ),
    ]
